---
format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: react-native
trigger_map:
- pull_request_source_branch: "*"
  workflow: primary

pipelines:
  deploy-demo:
    description: Runs JavaScript tests, and verifies iOS and Android debug builds
    stages:
    - test-and-build-debug: {}
  deploy:
    stages:
    - test-and-build-release: {}

stages:    
  test-and-build-debug:
    abort_on_fail: true
    workflows:
    - test-js: {}
    - deploy-ios-debug: {}
    - deploy-android-debug: {}
  test-and-build-release:
    abort_on_fail: true
    workflows:
    - test-js: {}
    - deploy-ios-release: {}
    - deploy-android-release: {}

workflows:
  _setup:
    steps:
    - git-clone@7: {}
    - restore-npm-cache@1: {}
    - npm@1:
        title: Install dependencies
        inputs:
        - command: install
    - save-npm-cache@1: {}

  test-js:
    before_run:
    - _setup
    steps:
    - npm@1:
        title: Run tests
        inputs:
        - command: run test-ci
    - custom-test-results-export:
        inputs:
        - test_name: Demo Test
        - search_pattern: "*/reports/*"
    - deploy-to-bitrise-io@2: {}

  primary:
    description: Runs JavaScript tests and deploys a test report.
    before_run:
    - test-js

  deploy-ios-debug:
    before_run:
    - _setup
    description: Builds the iOS version of the app for use in simulators
    steps:
    - react-native-bundle@1:
        inputs:
        - entry_file: index.js
        - platform: ios
    - restore-cocoapods-cache@1: {}
    - cocoapods-install@2: {}
    - xcode-build-for-simulator@0:
        inputs:
        - project_path: ios/BitriseReactNativeSample.xcworkspace
        - scheme: BitriseReactNativeSample
        - simulator_device: iPhone 13
        - configuration: Debug
    - script@1:
        inputs:
        - content: |-
            #!/usr/bin/env bash
            # fail if any commands fails
            set -e
            # debug log
            set -x
            # zip the app package
            cd $BITRISE_DEPLOY_DIR
            zip -r React\ Native\ Demo.app.zip React\ Native\ Demo.app
    - deploy-to-bitrise-io@2: {}
    - save-cocoapods-cache@1: {}

  deploy-android-debug:
    before_run:
    - _setup
    description: Builds the Android version of the app for use in emulators
    steps:
    - react-native-bundle@1:
        inputs:
        - entry_file: index.js
        - platform: android
    - restore-gradle-cache@1: {}
    - android-build@1:
        inputs:
        - module: app
        - project_location: android
        - variant: debug
    - deploy-to-bitrise-io@2: {}
    - save-gradle-cache@1: {}
    meta:
      bitrise.io:
        stack: linux-docker-android-20.04

  deploy-ios-release:
    before_run:
    - _setup
    description: Builds a release version of the iOS app
    steps:
    - react-native-bundle@1:
        inputs:
        - entry_file: index.js
        - platform: ios
    - cocoapods-install@2: {}
    - xcode-build-for-simulator@0:
        inputs:
        - project_path: ios/BitriseReactNativeSample.xcworkspace
        - scheme: BitriseReactNativeSample
        - simulator_device: iPhone 13
        - configuration: Release
    - deploy-to-bitrise-io@2: {}

  deploy-android-release:
    before_run:
    - _setup
    description: Builds a release version of the Android app
    steps:
    - react-native-bundle@1:
        inputs:
        - entry_file: index.js
        - platform: android
    - android-build@1:
        inputs:
        - module: app
        - project_location: android
        - variant: release
    - deploy-to-bitrise-io@2: {}
    meta:
      bitrise.io:
        stack: linux-docker-android-20.04
